"""Create a transparent, case-level boiling-hysteresis report from processed data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def analyze(processed_dir: Path) -> dict[str, object]:
    summary_path = processed_dir / "summary.json"
    thermal_path = processed_dir / "thermal_timeseries.csv"
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    thermal = pd.read_csv(thermal_path)
    t = thermal["time_reference_temperature_s"].to_numpy(float)
    q = thermal["heat_flux_W_cm2"].to_numpy(float)
    dt = thermal["wall_superheat_C"].to_numpy(float)
    off = summary.get("dc_shutoff_time_s")
    branch = np.where(np.isfinite(off) & (t >= float(off)), "cooling", "heating") if off is not None else np.full(len(t), "unclassified")
    thermal["hysteresis_branch"] = branch
    thermal.to_csv(processed_dir / "hysteresis_timeseries.csv", index=False)

    q_chf = summary.get("chf_proxy_W_cm2")
    q_nbr = summary.get("nbr_W_cm2")
    ratio = float(q_nbr / q_chf) if q_chf not in (None, 0) and q_nbr is not None else np.nan
    status = "screening_proxy" if summary.get("chf_event_status") != "confirmed_by_user" else "user_confirmed_proxy"
    rows = [{
        "test_id": summary.get("test_id"),
        "analysis_mode": summary.get("analysis_mode"),
        "pressure_kPa": summary.get("pressure_mean_kPa"),
        "surface_temperature_max_C": summary.get("max_surface_temp_C"),
        "q_chf_proxy_W_cm2": q_chf,
        "q_nbr_proxy_W_cm2": q_nbr,
        "hysteresis_ratio_qnbr_over_qchf_proxy": ratio,
        "chf_proxy_time_s": summary.get("chf_proxy_time_s"),
        "nbr_proxy_time_s": summary.get("nbr_time_s"),
        "dc_shutoff_time_s": off,
        "evidence_status": status,
        "definition": "q_NBR / q_CHF proxy using the upstream fixed-window marker; not an independently validated CHF measurement",
    }]
    result = pd.DataFrame(rows)
    result.to_csv(processed_dir / "hysteresis_summary.csv", index=False)
    try:
        with pd.ExcelWriter(processed_dir / "hysteresis_analysis.xlsx", engine="openpyxl") as writer:
            result.to_excel(writer, sheet_name="Summary", index=False)
            thermal.to_excel(writer, sheet_name="TimeSeries", index=False)
    except ImportError:
        pass

    plots_dir = processed_dir / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(8.5, 6.0))
    for name, color in (("heating", "tab:red"), ("cooling", "tab:blue"), ("unclassified", "0.5")):
        mask = branch == name
        if np.any(mask):
            ax.plot(dt[mask], q[mask], color=color, lw=1.2, label=name.capitalize())
    if q_chf is not None and summary.get("chf_proxy_time_s") is not None:
        i = int(np.nanargmin(np.abs(t - float(summary["chf_proxy_time_s"]))))
        ax.scatter([dt[i]], [q[i]], color="black", marker="x", s=60, label="CHF proxy marker")
    if q_nbr is not None and summary.get("nbr_time_s") is not None:
        i = int(np.nanargmin(np.abs(t - float(summary["nbr_time_s"]))))
        ax.scatter([dt[i]], [q[i]], color="black", marker="o", facecolors="none", s=65, label="NBR proxy marker")
    ax.set_xlabel(r"Wall superheat, $\Delta T_w$ (K)")
    ax.set_ylabel(r"Heat flux, $q''$ (W/cm$^2$)")
    ax.set_title(f"{summary.get('test_id', processed_dir.name)} boiling hysteresis")
    ax.grid(True, linestyle="--", alpha=0.35)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(plots_dir / "hysteresis_boiling_curve.png", dpi=200)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(5.5, 4.5))
    ax.bar(["q_NBR / q_CHF\n(proxy)"], [ratio], color="0.35")
    ax.set_ylabel("Hysteresis ratio")
    ax.set_title(f"{summary.get('test_id', processed_dir.name)}")
    ax.grid(True, axis="y", linestyle="--", alpha=0.35)
    fig.tight_layout()
    fig.savefig(plots_dir / "hysteresis_ratio.png", dpi=200)
    plt.close(fig)
    metadata = {
        "schema_version": "1.0",
        "source_summary": str(summary_path),
        "source_timeseries": str(thermal_path),
        "definition": rows[0]["definition"],
        "evidence_status": status,
        "meb_analysis": "retained only for subcooled BoilingBench-1; not generated by this script",
    }
    (processed_dir / "hysteresis_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return rows[0]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--processed-dir", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(analyze(args.processed_dir), indent=2))


if __name__ == "__main__":
    main()
